### PR TITLE
fix: handle special characters in commit messages

### LINKED ISSUE #55: Escape message text
Every time a commit has HTML special characters, such as:

```
Blabla

Co-authored-by: Ilya Semenov <ilya@semenov.co>
```

it won't deliver.

### PR DESCRIPTION
**Pull request by sekomer**
fixes #55

### CODE REVIEW

**Review by krcpa — APPROVED** [review]

File: src/webhooks/github/webhook_handlers/push.rs [hunk 1]
```diff
@@ -58,7 +59,7 @@ pub fn handle_push_event(body: &web::Bytes) -> String {
         log::info!("Commit author: {}", commit.author.name);
 
         let commit_url = &commit.url;
-        let commit_message = &commit.message.trim_end();
+        let commit_message = encode_text(commit.message.trim_end());
         let commit_author_name = &commit.author.name;
```
Comment (IlyaSemenov) [inline src/webhooks/github/webhook_handlers/push.rs:63]: This should probably be encoded, too, just in case if someone uses funny symbols in their names.

Comment (sekomer) [reply src/webhooks/github/webhook_handlers/push.rs]: done

**Comment by IlyaSemenov** [comment]
Looks good to me.

**Review by IlyaSemenov — APPROVED** [review]
